[package]
name = "monkey-rust"
version = "0.1.0"
authors = ["Esdras Amora"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = "4.1.13"
strum = { version = "0.24.1", features = ["derive"] }
